export const FINISH_QUIZ = 'finish_quiz'
export const CHANGE_QUESTION_QUIZ = 'change_question_quiz'
export const ADD_ANSWER_QUIZ = 'add_answer_quiz'
export const UPDATE_ANSWER_QUIZ = 'update_answer_quiz'
export const RESET_QUIZ = 'reset_quiz'
export const LOAD_QUIZ_DATA = 'load_quiz_data'
export const RESET_ANSWER_QUIZ = 'reset_answer_quiz'
